Nomeação e Telefone_membro
pedro-salviano/PIBD-2023-1-Solucao-1 pull request #4
Opened 2023-08-02 14:27 UTC by Thi08

2023-08-02 20:11 UTC, IvanCalvo requested changes
Acredito que não precise da sintexe FK_nome_da_chave, acho que pode deixar só o nome da chave mesmo

E também na primeira tabela acho que todos os atributos são chave primária

2023-08-02 20:25 UTC, IvanCalvo requested changes, later dismissed
Eu acho que falei errado, a PK do telefone tava certa, era a da nomeação que tinha que mudar e incluir a identidade da tabela coordenador_administrativo

e também acho que os nomes podem ficar só o atributo, tipo onde tá "reitoria_Inicio_periodo" deixar só como "Inicio_periodo"

2023-08-02 20:40 UTC, IvanCalvo commented
> e também acho que os nomes podem ficar só o atributo, tipo onde tá "reitoria_Inicio_periodo" deixar só como "Inicio_periodo"

só pra registrar aqui que eu tava errado spbre isso, acho que o ideal é deixar como "reitoria_Inicio_periodo" mesmo

2023-08-04 14:39 UTC, Pietro-MM requested changes, later dismissed

2023-08-04 14:39 UTC, Pietro-MM commented on esquema_fisico/01_table_telefone_membro.sql
Tabela ja produzida

2023-08-04 14:39 UTC, Pietro-MM commented on esquema_fisico/02_constraints_telefone_membro.sql
Tabela ja produzida

2023-08-04 14:39 UTC, Pietro-MM commented on esquema_fisico/01_table_nomeacao.sql
-  Nessa table, sera necessária a criação de um Surrogate, pois é um relacionamento N para M, em que N reitoria pode nomear M Coordenador Administrativo (Seguindo o DER). Basta criar um ID que sera a primary kei, e criar as colunas coordenador_administrativo_id e reitoria_id, que devem referenciar as tabelas coordeador_administrativo e reitoria_id como FK.

2023-08-05 02:49 UTC, pedro-salviano approved these changes

2023-08-05 02:56 UTC, pedro-salviano commented on esquema_fisico/01_table_nomeacao.sql
solved

2023-08-05 02:56 UTC, pinguim11 approved these changes

2023-08-05 02:56 UTC, ajuliasousa approved these changes

2023-08-05 02:57 UTC, merged