Artefatos pandolfi
pedro-salviano/PIBD-2023-1-Solucao-1 pull request #51
Opened 2023-09-05 23:57 UTC by pedro-salviano

2023-09-06 21:02 UTC, pedro-salviano commented
Essa pr são os artefatos do @Pandolfiz fiz o upload para ele, preciso que façam a review testes e o merge

2023-09-07 18:21 UTC, dahiwas requested changes
Na linha 65 está faltando, talvez se resolva com:
Acho que só tem um problema aqui, talvez resolva com:

```
CREATE OR REPLACE VIEW vDocumentos as 
SELECT 
		esp.Titulacao as Titulacao,
		esp.Tempo_de_atuacao as DisponibilidadeAutor,
		esp.Nivel_de_proficiencia as DeclaracaoProficiencia,
		esp.Diploma as Diploma, 
		ae.Comprovacao_profissional as RegistroMinistrante,
		esp.Comprovacao_de_vinculo as VinculoFile
FROM 
		especialista esp 
LEFT JOIN 
		membro_academico ma ON  esp.membro_academico_id = ma.id
LEFT JOIN
		aluno_professor_isf_id apISF ON ma.id = apISF.membro_academico_id
LEFT JOIN
		aluno_especializacao ae ON apISF.membro_academico_id = ae.aluno_professor_isf_id
``` 
Mas mesmo assim aluno_especializacao nao possui comprovacao_profissional

2023-09-07 18:21 UTC, dahiwas commented on esquema_fisico/funcoes/03_vDocumentos.sql
> +		aluno_especializacao ae ON  = ae.esp
Acho que só tem um problema aqui, talvez resolva com:
```
CREATE OR REPLACE VIEW vDocumentos as 
SELECT 
		esp.Titulacao as Titulacao,
		esp.Tempo_de_atuacao as DisponibilidadeAutor,
		esp.Nivel_de_proficiencia as DeclaracaoProficiencia,
		esp.Diploma as Diploma, 
		ae.Comprovacao_profissional as RegistroMinistrante,
		esp.Comprovacao_de_vinculo as VinculoFile
FROM 
		especialista esp 
LEFT JOIN 
		membro_academico ma ON  esp.membro_academico_id = ma.id
LEFT JOIN
		aluno_professor_isf_id apISF ON ma.id = apISF.membro_academico_id
LEFT JOIN
		aluno_especializacao ae ON apISF.membro_academico_id = ae.aluno_professor_isf_id 
```
Mas mesmo assim aluno_especalizacao nao possui comprovacao_profissional

2023-09-07 20:16 UTC, dahiwas approved these changes
Testado e está funcionando!

2023-09-07 20:16 UTC, merged