Update 02_constraints_material.sql
pedro-salviano/PIBD-2023-1-Solucao-1 pull request #6
Opened 2023-08-02 17:05 UTC by pinguim11

adição das constraints da tabela material

2023-08-04 14:40 UTC, Pietro-MM requested changes, later dismissed

2023-08-04 14:40 UTC, Pietro-MM commented on esquema_fisico/02_constraints_material.sql
- A tabela material existe mas ainda não foi declarada, recomendo a produação da mesma. Adicionar junto nesta PR.

2023-08-05 00:59 UTC, pedro-salviano approved these changes
LGTM!

2023-08-05 00:59 UTC, marshall1003 approved these changes

2023-08-05 01:00 UTC, Viniciusog approved these changes

2023-08-05 01:01 UTC, merged